import Link from 'next/link';
import type { Insight } from '@/lib/queries';

/**
 * One AI-written context card. The facts line is computed from the database;
 * the narrative is Claude's reading of exactly those facts, and is labelled
 * as such. The two are visually separated on purpose.
 */
export default function InsightCard({ insight }: { insight: Insight }) {
  const f = insight.facts as any;
  return (
    <article className="card insight">
      <div className="ch">
        <div>
          <b>{insight.headline}</b>
          <small>{insight.title} · {insight.source}</small>
        </div>
      </div>
      <p className="insightfacts">
        Now: <strong>{f.current} {insight.unit}</strong>
        {typeof f.percentile === 'number' && <> · {f.percentile}th percentile of {f.points} observations</>}
        {f.sinceLabel && <> · {f.sinceLabel}</>}
      </p>
      <div className="insightbody">
        {insight.body.split(/\n\n+/).map((p, i) => <p key={i}>{p}</p>)}
      </div>
      <div className="cfoot">
        <span>AI context · generated by {insight.model} from the verified numbers above · may misjudge causes</span>
        <span className="leg">
          <Link className="link" href={`/explore?x=${insight.seriesId}`} style={{ fontSize: 10 }}>
            Inspect the series
          </Link>
        </span>
      </div>
    </article>
  );
}
